// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct EquipList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EquipList GetRootAsEquipList(ByteBuffer _bb) { return GetRootAsEquipList(_bb, new EquipList()); }
  public static EquipList GetRootAsEquipList(ByteBuffer _bb, EquipList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EquipList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Equip? Equips(int j) { int o = __p.__offset(4); return o != 0 ? (Equip?)(new Equip()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EquipsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<EquipList> CreateEquipList(FlatBufferBuilder builder,
      VectorOffset EquipsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    EquipList.AddEquips(builder, EquipsOffset);
    return EquipList.EndEquipList(builder);
  }

  public static void StartEquipList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddEquips(FlatBufferBuilder builder, VectorOffset EquipsOffset) { builder.AddOffset(0, EquipsOffset.Value, 0); }
  public static VectorOffset CreateEquipsVector(FlatBufferBuilder builder, Offset<Equip>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEquipsVectorBlock(FlatBufferBuilder builder, Offset<Equip>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartEquipsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<EquipList> EndEquipList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EquipList>(o);
  }
};


}
