// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct GameLevelGradeList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameLevelGradeList GetRootAsGameLevelGradeList(ByteBuffer _bb) { return GetRootAsGameLevelGradeList(_bb, new GameLevelGradeList()); }
  public static GameLevelGradeList GetRootAsGameLevelGradeList(ByteBuffer _bb, GameLevelGradeList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameLevelGradeList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameLevelGrade? GameLevelGrades(int j) { int o = __p.__offset(4); return o != 0 ? (GameLevelGrade?)(new GameLevelGrade()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GameLevelGradesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameLevelGradeList> CreateGameLevelGradeList(FlatBufferBuilder builder,
      VectorOffset GameLevelGradesOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GameLevelGradeList.AddGameLevelGrades(builder, GameLevelGradesOffset);
    return GameLevelGradeList.EndGameLevelGradeList(builder);
  }

  public static void StartGameLevelGradeList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddGameLevelGrades(FlatBufferBuilder builder, VectorOffset GameLevelGradesOffset) { builder.AddOffset(0, GameLevelGradesOffset.Value, 0); }
  public static VectorOffset CreateGameLevelGradesVector(FlatBufferBuilder builder, Offset<GameLevelGrade>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGameLevelGradesVectorBlock(FlatBufferBuilder builder, Offset<GameLevelGrade>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGameLevelGradesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameLevelGradeList> EndGameLevelGradeList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameLevelGradeList>(o);
  }
};


}
