// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct GameLevelRegionList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameLevelRegionList GetRootAsGameLevelRegionList(ByteBuffer _bb) { return GetRootAsGameLevelRegionList(_bb, new GameLevelRegionList()); }
  public static GameLevelRegionList GetRootAsGameLevelRegionList(ByteBuffer _bb, GameLevelRegionList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameLevelRegionList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameLevelRegion? GameLevelRegions(int j) { int o = __p.__offset(4); return o != 0 ? (GameLevelRegion?)(new GameLevelRegion()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GameLevelRegionsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameLevelRegionList> CreateGameLevelRegionList(FlatBufferBuilder builder,
      VectorOffset GameLevelRegionsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GameLevelRegionList.AddGameLevelRegions(builder, GameLevelRegionsOffset);
    return GameLevelRegionList.EndGameLevelRegionList(builder);
  }

  public static void StartGameLevelRegionList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddGameLevelRegions(FlatBufferBuilder builder, VectorOffset GameLevelRegionsOffset) { builder.AddOffset(0, GameLevelRegionsOffset.Value, 0); }
  public static VectorOffset CreateGameLevelRegionsVector(FlatBufferBuilder builder, Offset<GameLevelRegion>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGameLevelRegionsVectorBlock(FlatBufferBuilder builder, Offset<GameLevelRegion>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGameLevelRegionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameLevelRegionList> EndGameLevelRegionList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameLevelRegionList>(o);
  }
};


}
