// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct MaterialList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MaterialList GetRootAsMaterialList(ByteBuffer _bb) { return GetRootAsMaterialList(_bb, new MaterialList()); }
  public static MaterialList GetRootAsMaterialList(ByteBuffer _bb, MaterialList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MaterialList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Material? Materials(int j) { int o = __p.__offset(4); return o != 0 ? (Material?)(new Material()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MaterialsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MaterialList> CreateMaterialList(FlatBufferBuilder builder,
      VectorOffset MaterialsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    MaterialList.AddMaterials(builder, MaterialsOffset);
    return MaterialList.EndMaterialList(builder);
  }

  public static void StartMaterialList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddMaterials(FlatBufferBuilder builder, VectorOffset MaterialsOffset) { builder.AddOffset(0, MaterialsOffset.Value, 0); }
  public static VectorOffset CreateMaterialsVector(FlatBufferBuilder builder, Offset<Material>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMaterialsVectorBlock(FlatBufferBuilder builder, Offset<Material>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMaterialsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MaterialList> EndMaterialList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MaterialList>(o);
  }
};


}
