// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct NPCList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NPCList GetRootAsNPCList(ByteBuffer _bb) { return GetRootAsNPCList(_bb, new NPCList()); }
  public static NPCList GetRootAsNPCList(ByteBuffer _bb, NPCList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NPCList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NPC? NPCs(int j) { int o = __p.__offset(4); return o != 0 ? (NPC?)(new NPC()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int NPCsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<NPCList> CreateNPCList(FlatBufferBuilder builder,
      VectorOffset NPCsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    NPCList.AddNPCs(builder, NPCsOffset);
    return NPCList.EndNPCList(builder);
  }

  public static void StartNPCList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddNPCs(FlatBufferBuilder builder, VectorOffset NPCsOffset) { builder.AddOffset(0, NPCsOffset.Value, 0); }
  public static VectorOffset CreateNPCsVector(FlatBufferBuilder builder, Offset<NPC>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNPCsVectorBlock(FlatBufferBuilder builder, Offset<NPC>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartNPCsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<NPCList> EndNPCList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NPCList>(o);
  }
};


}
