// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct RechargeShopList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RechargeShopList GetRootAsRechargeShopList(ByteBuffer _bb) { return GetRootAsRechargeShopList(_bb, new RechargeShopList()); }
  public static RechargeShopList GetRootAsRechargeShopList(ByteBuffer _bb, RechargeShopList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RechargeShopList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RechargeShop? RechargeShops(int j) { int o = __p.__offset(4); return o != 0 ? (RechargeShop?)(new RechargeShop()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RechargeShopsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<RechargeShopList> CreateRechargeShopList(FlatBufferBuilder builder,
      VectorOffset RechargeShopsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    RechargeShopList.AddRechargeShops(builder, RechargeShopsOffset);
    return RechargeShopList.EndRechargeShopList(builder);
  }

  public static void StartRechargeShopList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRechargeShops(FlatBufferBuilder builder, VectorOffset RechargeShopsOffset) { builder.AddOffset(0, RechargeShopsOffset.Value, 0); }
  public static VectorOffset CreateRechargeShopsVector(FlatBufferBuilder builder, Offset<RechargeShop>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRechargeShopsVectorBlock(FlatBufferBuilder builder, Offset<RechargeShop>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRechargeShopsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<RechargeShopList> EndRechargeShopList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RechargeShopList>(o);
  }
};


}
