// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct ShopCategory : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ShopCategory GetRootAsShopCategory(ByteBuffer _bb) { return GetRootAsShopCategory(_bb, new ShopCategory()); }
  public static ShopCategory GetRootAsShopCategory(ByteBuffer _bb, ShopCategory obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ShopCategory __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<ShopCategory> CreateShopCategory(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset NameOffset = default(StringOffset)) {
    builder.StartObject(2);
    ShopCategory.AddName(builder, NameOffset);
    ShopCategory.AddId(builder, Id);
    return ShopCategory.EndShopCategory(builder);
  }

  public static void StartShopCategory(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static Offset<ShopCategory> EndShopCategory(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ShopCategory>(o);
  }
};


}
