// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct SkillLevelList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SkillLevelList GetRootAsSkillLevelList(ByteBuffer _bb) { return GetRootAsSkillLevelList(_bb, new SkillLevelList()); }
  public static SkillLevelList GetRootAsSkillLevelList(ByteBuffer _bb, SkillLevelList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SkillLevelList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SkillLevel? SkillLevels(int j) { int o = __p.__offset(4); return o != 0 ? (SkillLevel?)(new SkillLevel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SkillLevelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SkillLevelList> CreateSkillLevelList(FlatBufferBuilder builder,
      VectorOffset SkillLevelsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    SkillLevelList.AddSkillLevels(builder, SkillLevelsOffset);
    return SkillLevelList.EndSkillLevelList(builder);
  }

  public static void StartSkillLevelList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSkillLevels(FlatBufferBuilder builder, VectorOffset SkillLevelsOffset) { builder.AddOffset(0, SkillLevelsOffset.Value, 0); }
  public static VectorOffset CreateSkillLevelsVector(FlatBufferBuilder builder, Offset<SkillLevel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSkillLevelsVectorBlock(FlatBufferBuilder builder, Offset<SkillLevel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSkillLevelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SkillLevelList> EndSkillLevelList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SkillLevelList>(o);
  }
};


}
