// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_UIFormList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_UIFormList GetRootAsSys_UIFormList(ByteBuffer _bb) { return GetRootAsSys_UIFormList(_bb, new Sys_UIFormList()); }
  public static Sys_UIFormList GetRootAsSys_UIFormList(ByteBuffer _bb, Sys_UIFormList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_UIFormList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Sys_UIForm? SysUIForms(int j) { int o = __p.__offset(4); return o != 0 ? (Sys_UIForm?)(new Sys_UIForm()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysUIFormsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sys_UIFormList> CreateSys_UIFormList(FlatBufferBuilder builder,
      VectorOffset Sys_UIFormsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sys_UIFormList.AddSysUIForms(builder, Sys_UIFormsOffset);
    return Sys_UIFormList.EndSys_UIFormList(builder);
  }

  public static void StartSys_UIFormList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSysUIForms(FlatBufferBuilder builder, VectorOffset SysUIFormsOffset) { builder.AddOffset(0, SysUIFormsOffset.Value, 0); }
  public static VectorOffset CreateSysUIFormsVector(FlatBufferBuilder builder, Offset<Sys_UIForm>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysUIFormsVectorBlock(FlatBufferBuilder builder, Offset<Sys_UIForm>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSysUIFormsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sys_UIFormList> EndSys_UIFormList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_UIFormList>(o);
  }
};


}
