// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_SceneDetailList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_SceneDetailList GetRootAsSys_SceneDetailList(ByteBuffer _bb) { return GetRootAsSys_SceneDetailList(_bb, new Sys_SceneDetailList()); }
  public static Sys_SceneDetailList GetRootAsSys_SceneDetailList(ByteBuffer _bb, Sys_SceneDetailList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_SceneDetailList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Sys_SceneDetail? SysSceneDetails(int j) { int o = __p.__offset(4); return o != 0 ? (Sys_SceneDetail?)(new Sys_SceneDetail()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysSceneDetailsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sys_SceneDetailList> CreateSys_SceneDetailList(FlatBufferBuilder builder,
      VectorOffset Sys_SceneDetailsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sys_SceneDetailList.AddSysSceneDetails(builder, Sys_SceneDetailsOffset);
    return Sys_SceneDetailList.EndSys_SceneDetailList(builder);
  }

  public static void StartSys_SceneDetailList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSysSceneDetails(FlatBufferBuilder builder, VectorOffset SysSceneDetailsOffset) { builder.AddOffset(0, SysSceneDetailsOffset.Value, 0); }
  public static VectorOffset CreateSysSceneDetailsVector(FlatBufferBuilder builder, Offset<Sys_SceneDetail>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysSceneDetailsVectorBlock(FlatBufferBuilder builder, Offset<Sys_SceneDetail>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSysSceneDetailsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sys_SceneDetailList> EndSys_SceneDetailList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_SceneDetailList>(o);
  }
};


}
