// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_CodeList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_CodeList GetRootAsSys_CodeList(ByteBuffer _bb) { return GetRootAsSys_CodeList(_bb, new Sys_CodeList()); }
  public static Sys_CodeList GetRootAsSys_CodeList(ByteBuffer _bb, Sys_CodeList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_CodeList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Sys_Code? SysCodes(int j) { int o = __p.__offset(4); return o != 0 ? (Sys_Code?)(new Sys_Code()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysCodesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sys_CodeList> CreateSys_CodeList(FlatBufferBuilder builder,
      VectorOffset Sys_CodesOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sys_CodeList.AddSysCodes(builder, Sys_CodesOffset);
    return Sys_CodeList.EndSys_CodeList(builder);
  }

  public static void StartSys_CodeList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSysCodes(FlatBufferBuilder builder, VectorOffset SysCodesOffset) { builder.AddOffset(0, SysCodesOffset.Value, 0); }
  public static VectorOffset CreateSysCodesVector(FlatBufferBuilder builder, Offset<Sys_Code>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysCodesVectorBlock(FlatBufferBuilder builder, Offset<Sys_Code>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSysCodesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sys_CodeList> EndSys_CodeList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_CodeList>(o);
  }
};


}
