// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_Audio : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_Audio GetRootAsSys_Audio(ByteBuffer _bb) { return GetRootAsSys_Audio(_bb, new Sys_Audio()); }
  public static Sys_Audio GetRootAsSys_Audio(ByteBuffer _bb, Sys_Audio obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_Audio __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Desc { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetDescBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescArray() { return __p.__vector_as_array<byte>(6); }
  public string AssetPath { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAssetPathBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetAssetPathBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetAssetPathArray() { return __p.__vector_as_array<byte>(8); }
  public int Is3D { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Volume { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Sys_Audio> CreateSys_Audio(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset DescOffset = default(StringOffset),
      StringOffset AssetPathOffset = default(StringOffset),
      int Is3D = 0,
      float Volume = 0.0f) {
    builder.StartObject(5);
    Sys_Audio.AddVolume(builder, Volume);
    Sys_Audio.AddIs3D(builder, Is3D);
    Sys_Audio.AddAssetPath(builder, AssetPathOffset);
    Sys_Audio.AddDesc(builder, DescOffset);
    Sys_Audio.AddId(builder, Id);
    return Sys_Audio.EndSys_Audio(builder);
  }

  public static void StartSys_Audio(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddDesc(FlatBufferBuilder builder, StringOffset DescOffset) { builder.AddOffset(1, DescOffset.Value, 0); }
  public static void AddAssetPath(FlatBufferBuilder builder, StringOffset AssetPathOffset) { builder.AddOffset(2, AssetPathOffset.Value, 0); }
  public static void AddIs3D(FlatBufferBuilder builder, int Is3D) { builder.AddInt(3, Is3D, 0); }
  public static void AddVolume(FlatBufferBuilder builder, float Volume) { builder.AddFloat(4, Volume, 0.0f); }
  public static Offset<Sys_Audio> EndSys_Audio(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_Audio>(o);
  }
};


}
