// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_CommonEventIdList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_CommonEventIdList GetRootAsSys_CommonEventIdList(ByteBuffer _bb) { return GetRootAsSys_CommonEventIdList(_bb, new Sys_CommonEventIdList()); }
  public static Sys_CommonEventIdList GetRootAsSys_CommonEventIdList(ByteBuffer _bb, Sys_CommonEventIdList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_CommonEventIdList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Sys_CommonEventId? SysCommonEventIds(int j) { int o = __p.__offset(4); return o != 0 ? (Sys_CommonEventId?)(new Sys_CommonEventId()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysCommonEventIdsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sys_CommonEventIdList> CreateSys_CommonEventIdList(FlatBufferBuilder builder,
      VectorOffset Sys_CommonEventIdsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sys_CommonEventIdList.AddSysCommonEventIds(builder, Sys_CommonEventIdsOffset);
    return Sys_CommonEventIdList.EndSys_CommonEventIdList(builder);
  }

  public static void StartSys_CommonEventIdList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSysCommonEventIds(FlatBufferBuilder builder, VectorOffset SysCommonEventIdsOffset) { builder.AddOffset(0, SysCommonEventIdsOffset.Value, 0); }
  public static VectorOffset CreateSysCommonEventIdsVector(FlatBufferBuilder builder, Offset<Sys_CommonEventId>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysCommonEventIdsVectorBlock(FlatBufferBuilder builder, Offset<Sys_CommonEventId>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSysCommonEventIdsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sys_CommonEventIdList> EndSys_CommonEventIdList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_CommonEventIdList>(o);
  }
};


}
