// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_SceneList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_SceneList GetRootAsSys_SceneList(ByteBuffer _bb) { return GetRootAsSys_SceneList(_bb, new Sys_SceneList()); }
  public static Sys_SceneList GetRootAsSys_SceneList(ByteBuffer _bb, Sys_SceneList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_SceneList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Sys_Scene? SysScenes(int j) { int o = __p.__offset(4); return o != 0 ? (Sys_Scene?)(new Sys_Scene()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysScenesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sys_SceneList> CreateSys_SceneList(FlatBufferBuilder builder,
      VectorOffset Sys_ScenesOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sys_SceneList.AddSysScenes(builder, Sys_ScenesOffset);
    return Sys_SceneList.EndSys_SceneList(builder);
  }

  public static void StartSys_SceneList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSysScenes(FlatBufferBuilder builder, VectorOffset SysScenesOffset) { builder.AddOffset(0, SysScenesOffset.Value, 0); }
  public static VectorOffset CreateSysScenesVector(FlatBufferBuilder builder, Offset<Sys_Scene>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysScenesVectorBlock(FlatBufferBuilder builder, Offset<Sys_Scene>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSysScenesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sys_SceneList> EndSys_SceneList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_SceneList>(o);
  }
};


}
