// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct Sys_AudioList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Sys_AudioList GetRootAsSys_AudioList(ByteBuffer _bb) { return GetRootAsSys_AudioList(_bb, new Sys_AudioList()); }
  public static Sys_AudioList GetRootAsSys_AudioList(ByteBuffer _bb, Sys_AudioList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Sys_AudioList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Sys_Audio? SysAudios(int j) { int o = __p.__offset(4); return o != 0 ? (Sys_Audio?)(new Sys_Audio()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysAudiosLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Sys_AudioList> CreateSys_AudioList(FlatBufferBuilder builder,
      VectorOffset Sys_AudiosOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Sys_AudioList.AddSysAudios(builder, Sys_AudiosOffset);
    return Sys_AudioList.EndSys_AudioList(builder);
  }

  public static void StartSys_AudioList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSysAudios(FlatBufferBuilder builder, VectorOffset SysAudiosOffset) { builder.AddOffset(0, SysAudiosOffset.Value, 0); }
  public static VectorOffset CreateSysAudiosVector(FlatBufferBuilder builder, Offset<Sys_Audio>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysAudiosVectorBlock(FlatBufferBuilder builder, Offset<Sys_Audio>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartSysAudiosVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Sys_AudioList> EndSys_AudioList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Sys_AudioList>(o);
  }
};


}
