// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct TaskList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static TaskList GetRootAsTaskList(ByteBuffer _bb) { return GetRootAsTaskList(_bb, new TaskList()); }
  public static TaskList GetRootAsTaskList(ByteBuffer _bb, TaskList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public TaskList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Task? Tasks(int j) { int o = __p.__offset(4); return o != 0 ? (Task?)(new Task()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TasksLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<TaskList> CreateTaskList(FlatBufferBuilder builder,
      VectorOffset TasksOffset = default(VectorOffset)) {
    builder.StartObject(1);
    TaskList.AddTasks(builder, TasksOffset);
    return TaskList.EndTaskList(builder);
  }

  public static void StartTaskList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddTasks(FlatBufferBuilder builder, VectorOffset TasksOffset) { builder.AddOffset(0, TasksOffset.Value, 0); }
  public static VectorOffset CreateTasksVector(FlatBufferBuilder builder, Offset<Task>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTasksVectorBlock(FlatBufferBuilder builder, Offset<Task>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTasksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<TaskList> EndTaskList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<TaskList>(o);
  }
};


}
