// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::FlatBuffers;

public struct WorldMapList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static WorldMapList GetRootAsWorldMapList(ByteBuffer _bb) { return GetRootAsWorldMapList(_bb, new WorldMapList()); }
  public static WorldMapList GetRootAsWorldMapList(ByteBuffer _bb, WorldMapList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public WorldMapList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WorldMap? WorldMaps(int j) { int o = __p.__offset(4); return o != 0 ? (WorldMap?)(new WorldMap()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int WorldMapsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<WorldMapList> CreateWorldMapList(FlatBufferBuilder builder,
      VectorOffset WorldMapsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    WorldMapList.AddWorldMaps(builder, WorldMapsOffset);
    return WorldMapList.EndWorldMapList(builder);
  }

  public static void StartWorldMapList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddWorldMaps(FlatBufferBuilder builder, VectorOffset WorldMapsOffset) { builder.AddOffset(0, WorldMapsOffset.Value, 0); }
  public static VectorOffset CreateWorldMapsVector(FlatBufferBuilder builder, Offset<WorldMap>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateWorldMapsVectorBlock(FlatBufferBuilder builder, Offset<WorldMap>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartWorldMapsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<WorldMapList> EndWorldMapList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<WorldMapList>(o);
  }
};


}
